// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using WebApplicationRabbitMQ.Data.Entities;

namespace WebApplicationRabbitMQ.Models;

public partial class Friend
{
    [Key]
    public int Id { get; set; }

    public string UserId { get; set; }

    public string FriendId { get; set; }

    public int InviteEnumId { get; set; }

    public bool DbStatus { get; set; }

    public DateTime DbCreatedOn { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual InviteEnum InviteEnum { get; set; }
}