// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplicationRabbitMQ.Models;

public partial class UsersGame
{
    public int Id { get; set; }

    public string UserId { get; set; }

    public int GameId { get; set; }

    public bool Creator { get; set; }

    public bool DbStatus { get; set; }

    public DateTime DbCreatedOn { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual Game Game { get; set; }
}